### ISSUE TITLE
Accessing lm.dev and domains

### ISSUE THREAD

**Issue by seivad** [koutsoumposval/laravel-microservices#1]
Hey great repo, i'm having trouble actually accessing lm.dev or any of the other domains I've added to my OS X hosts file as instructed. Chrome redirects to https:// and can't find it. 

Is there a trick to this when booting it up in Docker like exposing port 80 or something that isn't listed in the Readme docs?

**Comment by koutsoumposval** [comment]
Hello @seivad, this is indeed a known (stupid) issue for Chrome and `.dev` domains. A fast workaround is to open it with another browser. `.dev` should be changed to `.local` in order be functional in Chrome as well. I didn't had time to do it until now so feel free to make a PR for this.

**Comment by seivad** [comment]
Thanks bro, I thought it could have been something like that but with so many moving parts it was a bit hard to tell.

**Comment by koutsoumposval** [comment]
I updated the configuration and all services are now functional at a `.local` domain.
